import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import "./globals.css";
import Providers from "./providers";
import { DarkModeProvider } from '@/context/DarkModeContext';
const roboto = Roboto({
  subsets: ['latin'], // Choose the character subsets you need
  weight: ['400','500','100','900','300', '700'], // Include specific font weights (e.g., normal, bold)
  variable: '--font-roboto', // Add a custom CSS variable for the font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet"></link>
      <body
        className={`${roboto.variable} antialiased dark:bg-black`}
      >
        <DarkModeProvider>
        <Providers>
          {children}
        </Providers>
        </DarkModeProvider>
        
      </body>
    </html>
  );
}
